### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by timciep** [timciep/letterboxd-diary-embed#1]
- [x] handle not found usernames
- [x] custom domain name
- [x] landing page
- [ ] link to landing page at bottom of embed?
- [x] log source pages?
- [x] add to personal site
- [x] add to "work examples" on personal site

<img width="759" alt="image" src="https://github.com/timciep/letterboxd-diary-embed/assets/2245341/46e009cd-249c-4a79-9cc0-47cf41f2a0d3">
